//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.10 at 01:12:24 PM EST 
//


package com.acg.services.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="aaaDriveType" type="{http://acg.com/services/jaxb}aaaDriveDataType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "aaaDriveType"
})
@XmlRootElement(name = "aaaDriveResponse")
public class AaaDriveResponse {

    @XmlElement(required = true)
    protected AaaDriveDataType aaaDriveType;

    /**
     * Gets the value of the aaaDriveType property.
     * 
     * @return
     *     possible object is
     *     {@link AaaDriveDataType }
     *     
     */
    public AaaDriveDataType getAaaDriveType() {
        return aaaDriveType;
    }

    /**
     * Sets the value of the aaaDriveType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AaaDriveDataType }
     *     
     */
    public void setAaaDriveType(AaaDriveDataType value) {
        this.aaaDriveType = value;
    }

}
